# Generated by Django 3.2.16 on 2024-08-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_follow_unique_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
    ]
