# Generated by Django 3.2.16 on 2024-08-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
